spring:
  application:
    name: hr
  profiles:
    active: smart

hr:
  salary:
    - tier: aTier
      yearLimit: 10
      raisePercent: 10
    - tier: bTier
      yearLimit: 5
      raisePercent: 5
    - tier: cTier
      yearLimit: 2.5
      raisePercent: 2