spring:
  application:
    name: hr
  profiles:
    active: smart

hr:
  salary:
    aTier:
      yearLimit: 10
      raisePercent: 10
    bTier:
      yearLimit: 5
      raisePercent: 5
    cTier:
      yearLimit: 2
      raisePercent: 2