spring:
  application:
    name: hr
  profiles:
    active: smart
  datasource:
    url: jdbc:postgresql://localhost:5432/cubix-airport
    username: postgres
    password: nemmondommeg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hr:
  salary:
    def:
      raisePercent: 5
    smart:
      limits:
        10: 10
        5: 5
        2.5: 2